# Generated by Django 5.0.2 on 2024-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=213421, max_length=20),
            preserve_default=False,
        ),
    ]
