# Generated by Django 5.0.2 on 2024-02-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client_App', '0004_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at', '-start_date', '-end_date']},
        ),
    ]
