# Generated by Django 5.0.2 on 2024-02-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='end_booking',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='out_of_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='start_booking',
            field=models.DateField(blank=True, null=True),
        ),
    ]
