# Generated by Django 5.0.2 on 2024-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_App', '0007_alter_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='per_day_rent',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
    ]
