# Generated by Django 5.0.2 on 2024-02-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client_App', '0005_alter_booking_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
