# Generated by Django 5.0.2 on 2024-02-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_App', '0004_car_created_at_car_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-out_of_service', '-updated_at', '-created_at']},
        ),
    ]
