# Generated by Django 5.0.2 on 2024-02-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_App', '0006_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, upload_to='cars'),
        ),
    ]
